### ISSUE TITLE
Tubemap Hacking Roadmap

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/bh19_frontend#1]
- [ ] Grab example data state
- [ ] Change substitution text
- [ ] Introduce "link" mismatch type

**Comment by josiahseaman** [comment]
### Notes on Coding Changes
* Introducing "link" was many small changes in multiple places where there are else if "switch" statements:  drawMismatches(), reverseReversedReads() mm.seq =, drawSubstitution(), etc.
04fcfd9b8dff13598ca86bc9e4aebdc66f188043
